---
- name: Playbook to handle users
  hosts: Lab
  become: true
  collections:
    - freeipa.ansible_freeipa
  tasks:
  - name: Modificar Nombre.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      first: "{{ nombre }}"
    when:  nombre|string | length > 0
      
  - name: Modificar apellido.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      last: "{{ apellido }}"
    when:  apellido|string | length > 0
  
  - name: Modificar pass.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      userauthtype: otp
      password: "{{ pass }}"
      passwordexpiration: 2010-01-01
#       update_password: on_create
    when:  chpass|string == "SI"

  - name: Es admin
    ipagroup:
      ipaadmin_password: techadmin1234
      name: admins
      action: member
      user:
      - "{{ username }}"
    when: admin|string == "SI"

  - name: No es admin 
    ipagroup:
      ipaadmin_password: techadmin1234
      name: admins
      action: member
      user:
      - "{{ username }}"
      state: absent 
    when: admin|string == "NO"
    
  - name: rebuild user
    ipaautomember:
      ipaadmin_password: techadmin1234
      users:
      - "{{ username }}"
      state: rebuilt

# VOY A AGREGARLE EL REBUILD AL FINAL.
