---
- name: Baja de usuario.
  hosts: Lab
  become: true
  collections:
    - freeipa.ansible_freeipa
    
  tasks:
  - name: Eliminación de usuario.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      state: absent
