---
- name: Playbook to handle users
  hosts: Lab
  become: true
  collections:
    - freeipa.ansible_freeipa
    
  vars:
    si: "SI"
    
  tasks:
  - name: Modificar usuario.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      first: "{{ nombre }}"
      last: "{{ apellido }}"
      password: "{{ pass }}"
      update_password: on_create

  - name: Es admin
    ipasudorule:
      ipaadmin_password: techadmin1234
      name: test 
      user: "{{ username }}"
    assert: 
      that:
      - admin == si

#   - name: No es admin 
#     ipasudorule:
#       ipaadmin_password: techadmin1234
#       name: test
#       user: ""
#     when: "{{ admin }} == NO"
