---
- name: Alta de usuario.
  hosts: Lab
  become: true
  collections:
    - freeipa.ansible_freeipa
    
  tasks:
  - name: Definición de nombre de usuario.
    ipauser:
      ipaadmin_password: techadmin1234
      name: "{{ username }}"
      first: "{{ nombre }}"
      last: "{{ apellido }}"
      password: "{{ pass }}"
      update_password: on_create
      
  - name: Definición de privilegios de administrador.
    ipagroup:
      ipaadmin_password: techadmin1234
      name: admins
      action: member
      user:
      - "{{ username }}"
    when: admin|string == "SI"

#   - name: Definición de privilegios de administrador.
#     ipasudorule:
#       ipaadmin_password: techadmin1234
#       name: test 
#       user: "{{ username }}"
#     when: admin|string == "SI"
